###
GET http://localhost:8080/api/v1/categories?sort=name,desc&sort=id,desc

###
GET http://localhost:8080/api/v1/categories/10

###
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "",
  "description": "Mobile desc"
}

###
@id=6
DELETE http://localhost:8080/api/v1/categories/{{id}}